name: Linux Android SDK

on:
  push:
    branches: [ "linux-android-sdk" ]
  pull_request:
    branches: [ "linux-android-sdk" ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Find sdkmanager
      shell: bash
      run: |
        find $ANDROID_HOME -name "sdkmanager" -type f
